"""As-built documentation generator for Spec2Sphere.

Produces technical documentation, functional documentation, traceability matrices,
decision logs, reconciliation reports, and HTML/Markdown/PDF output.

All functions are pure Python (no DB calls). The ``data`` dict passed to each
function follows the structure returned by the pipeline context aggregator.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

_TEMPLATE_PATH = Path(__file__).parent.parent / "web" / "templates" / "doc_report.html"

_FALLBACK_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>{{ title }}</title>
<style>
body { font-family: sans-serif; color: #333; max-width: 1100px; margin: 0 auto; padding: 20px; }
.report-header { background: #05415A; color: white; padding: 24px; border-radius: 8px; margin-bottom: 24px; }
.report-header h1 { color: white; }
.report-header .subtitle { color: #C8963E; }
h2 { color: #05415A; border-left: 4px solid #C8963E; padding-left: 10px; margin-top: 30px; }
table { width: 100%; border-collapse: collapse; margin: 12px 0; }
th { background: #05415A; color: white; padding: 10px; text-align: left; }
td { padding: 8px 10px; border-bottom: 1px solid #eee; }
.sql-block { background: #263238; color: #eeffff; padding: 12px; border-radius: 4px; font-family: monospace; font-size: 13px; white-space: pre-wrap; }
.footer { text-align: center; color: #999; font-size: 12px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 16px; }
</style>
</head>
<body>
<div class="report-header">
  <h1>{{ title }}</h1>
  {% if subtitle %}<div class="subtitle">{{ subtitle }}</div>{% endif %}
  <div style="color:#aac8d4;font-size:13px;margin-top:8px;">
    Customer: {{ customer_name }} | Project: {{ project_name }} | {{ generated_at }}
  </div>
</div>
{% for section in sections %}
<h2>{{ section.title }}</h2>
<div>{{ section.html_content | safe }}</div>
{% endfor %}
{% if traceability_rows %}
<h2>Traceability Matrix</h2>
<table>
<thead><tr><th>Requirement</th><th>HLA Decision</th><th>Tech Objects</th><th>Test Cases</th><th>Result</th></tr></thead>
<tbody>
{% for row in traceability_rows %}
<tr>
  <td>{{ row.requirement }}</td>
  <td>{{ row.hla_decision }}</td>
  <td>{{ row.tech_objects | join(', ') }}</td>
  <td>{{ row.test_cases | join(', ') }}</td>
  <td>{{ row.result }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% if decision_log %}
<h2>Architecture Decision Log</h2>
<table>
<thead><tr><th>Topic</th><th>Choice</th><th>Rationale</th><th>Platform</th></tr></thead>
<tbody>
{% for d in decision_log %}
<tr><td>{{ d.topic }}</td><td>{{ d.choice }}</td><td>{{ d.rationale }}</td><td>{{ d.platform_placement }}</td></tr>
{% endfor %}
</tbody>
</table>
{% endif %}
{% if technical_objects %}
<h2>Technical Object Inventory</h2>
<table>
<thead><tr><th>Name</th><th>Type</th><th>Platform</th><th>Layer</th><th>Status</th></tr></thead>
<tbody>
{% for obj in technical_objects %}
<tr>
  <td><code>{{ obj.name }}</code></td>
  <td>{{ obj.object_type }}</td>
  <td>{{ obj.platform }}</td>
  <td>{{ obj.layer }}</td>
  <td>{{ obj.status }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endif %}
<div class="footer">Generated by Spec2Sphere &mdash; {{ generated_at }}</div>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Data extraction helpers
# ---------------------------------------------------------------------------


def _project_name(data: dict) -> str:
    return data.get("project", {}).get("name", "Unknown Project")


def _customer_name(data: dict) -> str:
    return data.get("customer", {}).get("name", "Unknown Customer")


def _parse_jsonb(value):
    """Parse a JSONB field that may be a string (asyncpg sometimes returns text)."""
    if isinstance(value, str):
        import json  # noqa: PLC0415

        try:
            return json.loads(value)
        except (json.JSONDecodeError, ValueError):
            return value
    return value


def _all_tech_objects(data: dict) -> list[dict]:
    """Merge explicit technical_objects list with objects embedded in tech_specs."""
    objects: list[dict] = list(data.get("technical_objects", []))
    seen_names = {o.get("name") for o in objects if isinstance(o, dict)}
    for spec in data.get("tech_specs", []):
        spec_objects = _parse_jsonb(spec.get("objects", []))
        if not isinstance(spec_objects, list):
            continue
        for obj in spec_objects:
            if not isinstance(obj, dict):
                continue
            name = obj.get("name")
            if name and name not in seen_names:
                objects.append(obj)
                seen_names.add(name)
    return objects


def _deployment_order(data: dict) -> list[str]:
    for spec in data.get("tech_specs", []):
        order = _parse_jsonb(spec.get("deployment_order"))
        if order and isinstance(order, list):
            return list(order)
    return []


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_technical_doc(data: dict) -> dict:
    """Return technical documentation as a markdown string.

    Covers all technical_objects (name, type, platform, layer, status, SQL)
    and deployment ordering from tech_specs.

    Returns:
        {title, content (markdown), deployment_order (list[str]), object_count (int)}
    """
    project_name = _project_name(data)
    objects = _all_tech_objects(data)
    deployment_order = _deployment_order(data)

    lines: list[str] = [
        f"# Technical Documentation — {project_name}",
        "",
        "## Technical Objects",
        "",
    ]

    if not objects:
        lines.append("_No technical objects defined._")
    else:
        for obj in objects:
            name = obj.get("name", "unnamed")
            otype = obj.get("object_type", "—")
            platform = obj.get("platform", "—")
            layer = obj.get("layer", "—")
            status = obj.get("status", "—")
            artifact = obj.get("generated_artifact", "")

            lines.append(f"### `{name}`")
            lines.append("")
            lines.append(f"- **Type:** {otype}")
            lines.append(f"- **Platform:** {platform}")
            lines.append(f"- **Layer:** {layer}")
            lines.append(f"- **Status:** {status}")
            if artifact:
                lines.append("")
                lines.append("**Generated Artifact:**")
                lines.append("")
                lines.append("```sql")
                lines.append(artifact)
                lines.append("```")
            lines.append("")

    if deployment_order:
        lines.append("## Deployment Order")
        lines.append("")
        for i, item in enumerate(deployment_order, 1):
            lines.append(f"{i}. `{item}`")
        lines.append("")

    return {
        "title": f"Technical Documentation — {project_name}",
        "content": "\n".join(lines),
        "deployment_order": deployment_order,
        "object_count": len(objects),
    }


def generate_functional_doc(data: dict) -> dict:
    """Return functional documentation as a markdown string.

    Covers requirements with business domain, KPIs (name + formula), parsed entities.

    Returns:
        {title, content (markdown)}
    """
    project_name = _project_name(data)
    requirements = data.get("requirements", [])

    lines: list[str] = [
        f"# Functional Documentation — {project_name}",
        "",
        "## Requirements",
        "",
    ]

    if not requirements:
        lines.append("_No requirements defined._")
    else:
        for req in requirements:
            req_id = req.get("id", "—")
            title = req.get("title", "Untitled")
            domain = req.get("business_domain", "—")
            status = req.get("status", "—")

            lines.append(f"### {title}")
            lines.append("")
            lines.append(f"- **ID:** {req_id}")
            lines.append(f"- **Business Domain:** {domain}")
            lines.append(f"- **Status:** {status}")

            # KPIs
            kpis = _parse_jsonb(req.get("parsed_kpis", []))
            if isinstance(kpis, list) and kpis:
                lines.append("")
                lines.append("**KPIs:**")
                lines.append("")
                for kpi in kpis:
                    if not isinstance(kpi, dict):
                        continue
                    kpi_name = kpi.get("name", "unnamed")
                    formula = kpi.get("formula", "")
                    if formula:
                        lines.append(f"- **{kpi_name}**: `{formula}`")
                    else:
                        lines.append(f"- **{kpi_name}**")

            # Parsed entities
            entities = _parse_jsonb(req.get("parsed_entities", {}))
            if entities:
                lines.append("")
                lines.append("**Entities:**")
                lines.append("")
                for entity_type, entity_list in entities.items():
                    if isinstance(entity_list, list):
                        names = ", ".join(str(e) for e in entity_list)
                    else:
                        names = str(entity_list)
                    lines.append(f"- **{entity_type}:** {names}")

            lines.append("")

    return {
        "title": f"Functional Documentation — {project_name}",
        "content": "\n".join(lines),
    }


def generate_traceability_matrix(data: dict) -> dict:
    """Build a traceability matrix linking requirements to HLA decisions,
    technical objects, test cases, and reconciliation results.

    Returns:
        {rows: list[{requirement, hla_decision, tech_objects, test_cases, result, result_class}]}
    """
    requirements = data.get("requirements", [])
    hla_documents = data.get("hla_documents", [])
    tech_specs = data.get("tech_specs", [])
    reconciliation_results = data.get("reconciliation_results", [])
    technical_objects = _all_tech_objects(data)

    # Build lookup: first hla narrative (simplification — real traceability would use IDs)
    hla_narrative = hla_documents[0].get("narrative", "—") if hla_documents else "—"

    # Collect all object names
    all_obj_names = [obj.get("name", "") for obj in technical_objects if obj.get("name")]

    # Collect all test case keys
    all_test_keys = [r.get("test_case_key", "") for r in reconciliation_results if r.get("test_case_key")]

    # Determine aggregate result
    def _aggregate_result(rec_results: list[dict]) -> tuple[str, str]:
        if not rec_results:
            return "no tests", "draft"
        statuses = [r.get("delta_status", "unknown") for r in rec_results]
        if any(s == "fail" for s in statuses):
            return "fail", "fail"
        if any(s == "tolerance" for s in statuses):
            return "tolerance", "tolerance"
        return "pass", "pass"

    rows: list[dict] = []

    if not requirements:
        # At minimum one row from whatever we have
        result, result_class = _aggregate_result(reconciliation_results)
        rows.append(
            {
                "requirement": "—",
                "hla_decision": hla_narrative[:80] if hla_narrative else "—",
                "tech_objects": all_obj_names[:5],
                "test_cases": all_test_keys[:5],
                "result": result,
                "result_class": result_class,
            }
        )
    else:
        for req in requirements:
            title = req.get("title", req.get("id", "—"))
            result, result_class = _aggregate_result(reconciliation_results)
            rows.append(
                {
                    "requirement": title,
                    "hla_decision": hla_narrative[:80] if hla_narrative else "—",
                    "tech_objects": all_obj_names,
                    "test_cases": all_test_keys,
                    "result": result,
                    "result_class": result_class,
                }
            )

    return {"rows": rows}


def generate_decision_log(data: dict) -> list[dict]:
    """Extract architecture decisions.

    Returns:
        list of {topic, choice, rationale, alternatives, platform_placement}
    """
    decisions = data.get("architecture_decisions", [])
    log: list[dict] = []
    for dec in decisions:
        log.append(
            {
                "topic": dec.get("topic", "—"),
                "choice": dec.get("choice", "—"),
                "rationale": dec.get("rationale", "—"),
                "alternatives": dec.get("alternatives", []),
                "platform_placement": dec.get("platform_placement", "—"),
            }
        )
    return log


def generate_reconciliation_report(data: dict) -> dict:
    """Summarise reconciliation results.

    Returns:
        {total_tests, passed, tolerance, expected_change, failed, results}
    """
    results = data.get("reconciliation_results", [])
    passed = 0
    tolerance = 0
    failed = 0
    expected_change = 0

    for r in results:
        status = r.get("delta_status", "").lower()
        if status == "pass":
            passed += 1
        elif status == "tolerance":
            tolerance += 1
        elif status == "fail":
            failed += 1
        elif status == "expected_change":
            expected_change += 1

    return {
        "total_tests": len(results),
        "passed": passed,
        "tolerance": tolerance,
        "expected_change": expected_change,
        "failed": failed,
        "results": results,
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _md_to_simple_html(md: str) -> str:
    """Minimal markdown-to-HTML converter for inline rendering.

    Handles: h1-h3, bold, code spans, code blocks, bullet lists, line breaks.
    """
    lines = md.split("\n")
    html_lines: list[str] = []
    in_code_block = False
    in_list = False

    for line in lines:
        # Code block toggle
        if line.strip().startswith("```"):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            if in_code_block:
                html_lines.append("</code></pre>")
                in_code_block = False
            else:
                lang = line.strip()[3:].strip() or ""
                html_lines.append(f'<pre class="sql-block"><code class="{lang}">')
                in_code_block = True
            continue

        if in_code_block:
            html_lines.append(line)
            continue

        # Headings
        if line.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = line[4:].strip()
            html_lines.append(f"<h3>{content}</h3>")
            continue
        if line.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = line[3:].strip()
            html_lines.append(f"<h2>{content}</h2>")
            continue
        if line.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = line[2:].strip()
            html_lines.append(f"<h1>{content}</h1>")
            continue

        # Bullet list
        if line.startswith("- "):
            if not in_list:
                html_lines.append("<ul>")
                in_list = True
            content = line[2:]
            content = _inline_md(content)
            html_lines.append(f"<li>{content}</li>")
            continue

        # Numbered list
        num_match = re.match(r"^(\d+)\. (.*)", line)
        if num_match:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = _inline_md(num_match.group(2))
            html_lines.append(f"<p>{num_match.group(1)}. {content}</p>")
            continue

        # Close list if needed
        if in_list and line.strip() == "":
            html_lines.append("</ul>")
            in_list = False

        if line.strip() == "":
            html_lines.append("<br>")
        else:
            content = _inline_md(line)
            html_lines.append(f"<p>{content}</p>")

    if in_list:
        html_lines.append("</ul>")
    if in_code_block:
        html_lines.append("</code></pre>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, code) to HTML."""
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Code span
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    return text


def render_html_report(data: dict) -> str:
    """Render full as-built report as self-contained HTML.

    Uses the Jinja2 template at _TEMPLATE_PATH; falls back to _FALLBACK_TEMPLATE
    if the file isn't found.

    Returns:
        HTML string
    """
    from jinja2 import Template  # noqa: PLC0415

    project = data.get("project", {})
    customer = data.get("customer", {})
    project_name = project.get("name", "Unknown Project")
    customer_name = customer.get("name", "Unknown Customer")
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Assemble sub-documents
    tech_doc = generate_technical_doc(data)
    func_doc = generate_functional_doc(data)
    recon_report = generate_reconciliation_report(data)
    traceability = generate_traceability_matrix(data)
    decision_log = generate_decision_log(data)

    technical_objects = _all_tech_objects(data)
    requirements = data.get("requirements", [])

    # Summary cards
    summary_cards = [
        {"value": len(requirements), "label": "Requirements"},
        {"value": tech_doc["object_count"], "label": "Technical Objects"},
        {"value": recon_report["total_tests"], "label": "Test Cases"},
        {"value": recon_report["passed"], "label": "Tests Passed"},
    ]

    # Sections
    sections = [
        {
            "title": "Functional Overview",
            "html_content": _md_to_simple_html(func_doc["content"]),
        },
        {
            "title": "Technical Specification",
            "html_content": _md_to_simple_html(tech_doc["content"]),
        },
    ]

    reconciliation = {
        "total_tests": recon_report["total_tests"],
        "passed": recon_report["passed"],
        "tolerance": recon_report["tolerance"],
        "failed": recon_report["failed"],
    }

    template_src: str
    if _TEMPLATE_PATH.exists():
        template_src = _TEMPLATE_PATH.read_text()
    else:
        template_src = _FALLBACK_TEMPLATE

    template = Template(template_src)
    return template.render(
        title=f"As-Built Documentation — {project_name}",
        subtitle=f"Customer: {customer_name}",
        customer_name=customer_name,
        project_name=project_name,
        generated_at=generated_at,
        summary_cards=summary_cards,
        sections=sections,
        traceability_rows=traceability["rows"],
        decision_log=decision_log,
        reconciliation=reconciliation,
        technical_objects=technical_objects,
    )


def render_markdown_report(data: dict) -> str:
    """Render a full as-built report as Markdown.

    Combines functional doc, technical doc, traceability table, decision log,
    and reconciliation summary into a single markdown string.

    Returns:
        Markdown string
    """
    project_name = _project_name(data)
    customer_name = _customer_name(data)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    tech_doc = generate_technical_doc(data)
    func_doc = generate_functional_doc(data)
    recon_report = generate_reconciliation_report(data)
    traceability = generate_traceability_matrix(data)
    decision_log = generate_decision_log(data)

    lines: list[str] = [
        f"# As-Built Documentation — {project_name}",
        "",
        f"**Customer:** {customer_name}  ",
        f"**Generated:** {generated_at}",
        "",
        "---",
        "",
        func_doc["content"],
        "",
        "---",
        "",
        tech_doc["content"],
        "",
        "---",
        "",
        "## Traceability Matrix",
        "",
        "| Requirement | HLA Decision | Tech Objects | Test Cases | Result |",
        "|---|---|---|---|---|",
    ]

    for row in traceability["rows"]:
        req = row["requirement"]
        hla = row["hla_decision"]
        objs = ", ".join(row["tech_objects"]) if row["tech_objects"] else "—"
        tcs = ", ".join(row["test_cases"]) if row["test_cases"] else "—"
        result = row["result"]
        lines.append(f"| {req} | {hla} | {objs} | {tcs} | {result} |")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Architecture Decision Log",
            "",
        ]
    )

    if decision_log:
        lines.extend(
            [
                "| Topic | Choice | Rationale | Platform |",
                "|---|---|---|---|",
            ]
        )
        for dec in decision_log:
            topic = dec["topic"]
            choice = dec["choice"]
            rationale = dec["rationale"]
            platform = dec["platform_placement"]
            lines.append(f"| {topic} | {choice} | {rationale} | {platform} |")
    else:
        lines.append("_No architecture decisions recorded._")

    lines.extend(
        [
            "",
            "---",
            "",
            "## Reconciliation Summary",
            "",
            f"- **Total Tests:** {recon_report['total_tests']}",
            f"- **Passed:** {recon_report['passed']}",
            f"- **Within Tolerance:** {recon_report['tolerance']}",
            f"- **Failed:** {recon_report['failed']}",
            "",
        ]
    )

    return "\n".join(lines)


def render_pdf_report(data: dict) -> bytes:
    """Render the as-built report as PDF bytes.

    Uses weasyprint to convert the HTML report to PDF.
    Falls back to returning the HTML as bytes if weasyprint is not installed.

    Returns:
        PDF bytes (or HTML bytes if weasyprint unavailable)
    """
    html = render_html_report(data)
    try:
        from weasyprint import HTML  # noqa: PLC0415

        return HTML(string=html).write_pdf()
    except ImportError:
        return html.encode("utf-8")


import logging as _logging  # noqa: E402

logger = _logging.getLogger(__name__)


async def sync_to_doc_platform(
    platform_type: str,
    html_content: str,
    title: str,
    space_name: str = "Spec2Sphere",
) -> dict:
    """Push generated documentation to a doc platform (BookStack/Confluence/Outline).

    Returns: {synced: bool, url: str|None, error: str|None}
    """
    try:
        import os as _os

        if platform_type == "bookstack":
            from spec2sphere.doc_platform.bookstack import BookStackAdapter  # noqa: PLC0415

            adapter = BookStackAdapter(
                base_url=_os.environ.get("BOOKSTACK_URL", ""),
                token_id=_os.environ.get("BOOKSTACK_TOKEN_ID", ""),
                token_secret=_os.environ.get("BOOKSTACK_TOKEN_SECRET", ""),
            )
        elif platform_type == "confluence":
            from spec2sphere.doc_platform.confluence import ConfluenceAdapter  # noqa: PLC0415

            adapter = ConfluenceAdapter(
                url=_os.environ.get("CONFLUENCE_URL", ""),
                token=_os.environ.get("CONFLUENCE_TOKEN", ""),
            )
        elif platform_type == "outline":
            from spec2sphere.doc_platform.outline import OutlineAdapter  # noqa: PLC0415

            adapter = OutlineAdapter(
                base_url=_os.environ.get("OUTLINE_URL", ""),
                api_key=_os.environ.get("OUTLINE_API_KEY", ""),
            )
        else:
            return {"synced": False, "url": None, "error": f"Unknown platform: {platform_type}"}

        space = await adapter.create_space(space_name, "Auto-generated by Spec2Sphere")
        page = await adapter.create_page(space.id, title, html_content)
        return {"synced": True, "url": page.url, "error": None}
    except Exception as exc:
        logger.warning("Doc platform sync failed (%s): %s", platform_type, exc)
        return {"synced": False, "url": None, "error": str(exc)}
