"""Live adapter — FastAPI router mounted at ``/v1/*`` on the dsp-ai service.

Session A exposes the minimum surface to unblock the Studio preview flow:
``POST /v1/enhance/{id}`` with Redis cache + engine, plus ``/healthz`` and
``/readyz``. SSE + telemetry land in Session B.

Session B adds: actions run, SSE stream, why provenance, telemetry ingest.
"""

from __future__ import annotations

import json  # noqa: F401 — used in why() and stream() function bodies
import logging
from typing import Any

from fastapi import APIRouter, Body, HTTPException
from pydantic import BaseModel

from .. import cache
from ..config import EnhancementMode
from ..engine import run_engine

logger = logging.getLogger(__name__)

router = APIRouter()


class EnhanceRequest(BaseModel):
    user: str | None = None
    context_hints: dict[str, Any] = {}
    context_key: str | None = None
    preview: bool = False


@router.post("/v1/enhance/{enhancement_id}")
async def enhance(enhancement_id: str, body: EnhanceRequest = Body(default=None)) -> dict:
    """Run an enhancement. Preview bypasses cache + skips DSP write-back."""
    body = body or EnhanceRequest()
    key = cache.key_for(enhancement_id, body.user, body.context_hints)

    if not body.preview:
        cached = await cache.get(key)
        if cached:
            cached["_cached"] = True
            return cached

    try:
        result = await run_engine(
            enhancement_id,
            user_id=body.user,
            context_hints=body.context_hints,
            context_key=body.context_key,
            mode_override=EnhancementMode.LIVE if body.preview else None,
            preview=body.preview,
        )
    except LookupError:
        raise HTTPException(status_code=404, detail="enhancement not found")

    if not body.preview:
        await cache.set_(key, result, ttl=600)
    return result


@router.post("/v1/actions/{enhancement_id}/run")
async def run_action(enhancement_id: str, body: EnhanceRequest = Body(default=None)) -> dict:
    """Synchronous click-to-run action. No cache. Full shaped output."""
    body = body or EnhanceRequest()
    try:
        return await run_engine(
            enhancement_id,
            user_id=body.user,
            context_hints=body.context_hints,
            context_key=body.context_key,
            mode_override=EnhancementMode.LIVE,
        )
    except LookupError:
        raise HTTPException(status_code=404, detail="enhancement not found")


@router.get("/v1/stream/{enhancement_id}/{user_id}")
async def stream(enhancement_id: str, user_id: str):
    """SSE stream — pushes ``briefing_generated`` events filtered by enhancement + user."""
    from sse_starlette.sse import EventSourceResponse  # noqa: PLC0415

    from ..events import subscribe  # noqa: PLC0415

    async def gen():
        async for ev in subscribe("briefing_generated"):
            if ev.get("enhancement_id") == enhancement_id and ev.get("user_id") == user_id:
                yield {"event": "briefing_generated", "data": json.dumps(ev)}

    return EventSourceResponse(gen())


@router.post("/v1/why/{generation_id}")
async def why(generation_id: str) -> dict:
    """Return provenance + 1-hop brain expansion for a completed generation."""
    import asyncpg  # noqa: PLC0415

    from ..settings import postgres_dsn  # noqa: PLC0415

    conn = await asyncpg.connect(postgres_dsn())
    try:
        row = await conn.fetchrow(
            "SELECT g.id::text AS gen_id, g.enhancement_id::text AS eid, g.user_id, g.context_key, "
            "g.prompt_hash, g.input_ids, g.model, g.quality_level, g.latency_ms, "
            "g.tokens_in, g.tokens_out, g.cost_usd, g.cached, g.quality_warnings, g.error_kind, "
            "g.preview, g.created_at, "
            "e.name AS enh_name, e.version AS enh_version "
            "FROM dsp_ai.generations g "
            "JOIN dsp_ai.enhancements e ON e.id = g.enhancement_id "
            "WHERE g.id = $1::uuid",
            generation_id,
        )
    finally:
        await conn.close()

    if row is None:
        raise HTTPException(status_code=404, detail="generation not found")

    input_ids_raw = row["input_ids"] or []
    # input_ids is JSONB; asyncpg may return a str or list — handle both.
    if isinstance(input_ids_raw, str):
        try:
            input_ids = json.loads(input_ids_raw)
        except Exception:
            input_ids = []
    else:
        input_ids = list(input_ids_raw)

    hop: list[dict] = []
    if input_ids:
        try:
            from ..brain.client import run as brain_run  # noqa: PLC0415

            hop = await brain_run(
                "MATCH (n) WHERE n.id IN $ids "
                "OPTIONAL MATCH (n)-[r]-(m) "
                "RETURN n, collect({edge: type(r), other: m.id}) AS neighbors LIMIT 20",
                ids=input_ids,
            )
        except Exception:
            hop = []  # Brain down ≠ 500; we still return provenance

    narrative = (
        f"Generated by `{row['model']}` (quality {row['quality_level']}) "
        f"at {row['created_at']}. Took {row['latency_ms']}ms. "
        f"Fed by {len(input_ids)} input node(s)."
    )
    warnings = row["quality_warnings"]
    if warnings:
        narrative += f" Quality warnings: {warnings}."

    return {
        "generation_id": row["gen_id"],
        "enhancement": {"name": row["enh_name"], "version": row["enh_version"]},
        "narrative": narrative,
        "provenance": {
            "user_id": row["user_id"],
            "context_key": row["context_key"],
            "prompt_hash": row["prompt_hash"],
            "input_ids": input_ids,
            "model": row["model"],
            "quality_level": row["quality_level"],
            "latency_ms": row["latency_ms"],
            "tokens_in": row["tokens_in"],
            "tokens_out": row["tokens_out"],
            "cost_usd": float(row["cost_usd"]) if row["cost_usd"] is not None else None,
            "cached": row["cached"],
            "error_kind": row["error_kind"],
            "preview": row["preview"],
            "created_at": row["created_at"].isoformat() if row["created_at"] else None,
        },
        "brain_one_hop": hop,
    }


class TelemetryEvent(BaseModel):
    kind: str  # widget.rendered | widget.dwelled | widget.clicked | widget.declined
    user_id: str
    enhancement_id: str | None = None
    object_id: str | None = None
    duration_s: float | None = None
    details: dict[str, Any] = {}


@router.post("/v1/telemetry")
async def telemetry(body: TelemetryEvent) -> dict:
    """Best-effort telemetry ingest. Never fails the caller."""
    try:
        from ..brain.feeders.behavior import record_event  # noqa: PLC0415

        await record_event(body)
    except Exception:
        logger.exception("telemetry: record_event failed (best-effort)")
    return {"ok": True}


@router.get("/v1/healthz")
async def healthz() -> dict:
    return {"status": "ok"}


@router.get("/v1/readyz")
async def readyz() -> dict:
    """Best-effort pings on each dependency; degrades gracefully."""
    warnings: list[str] = []

    try:
        import asyncpg

        from ..settings import postgres_dsn

        conn = await asyncpg.connect(postgres_dsn())
        await conn.close()
    except Exception:
        warnings.append("postgres")

    try:
        await cache._get().ping()
    except Exception:
        warnings.append("redis")

    return {"status": "ok", "warnings": warnings}
